#! /usr/bin/python3
import sys
from classes.Atlas import Atlas


"""
this is the file where the atlas object's initialized and where it runs waiting for a command to be given
"""

ARGS = sys.argv


def main():
    atlas = Atlas(commands=ARGS)
    atlas.run()


if __name__ == "__main__":
    main()
